version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "main"
    versioning-strategy: "lockfile-only"
    reviewers:
      - 'zivkovicmilos'
  - package-ecosystem: npm
    directory: /
    target-branch: 'main'
    schedule:
      interval: weekly
    groups:
      types-updates:
        patterns:
          - "@types/*"
      package-updates:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - 'zivkovicmilos'
